# Generated by Django 4.2 on 2023-06-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "articles",
            "0003_alter_article_abstract_alter_article_acceptance_date_and_more",
        ),
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.article"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="author_order",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
