# Generated by Django 4.2.2 on 2023-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_alter_author_article_id_alter_author_author_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
