# Generated by Django 4.2.5 on 2023-11-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_alter_author_first_name_alter_author_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authoridentifier",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="authors.author",
            ),
        ),
    ]
