PARTNERS = [
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "CERN",
    "China",
    "Czech Republic",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hong-Kong",
    "Hungary",
    "Iceland",
    "Israel",
    "Italy",
    "Japan",
    "JINR",
    "Mexico",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Slovak Republic",
    "South Africa",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Turkey",
    "United Kingdom",
    "United States",
]
