export const PARTNER_COUNTRIES = [
  "Australia",
  "Austria",
  "Belgium",
  "Canada",
  "China",
  "CERN",
  "Czechia",
  "Denmark",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "Israel",
  "Italy",
  "Japan",
  "JINR",
  "Korea, Republic of",
  "Mexico",
  "Netherlands",
  "Norway",
  "Poland",
  "Portugal",
  "Slovakia",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan, Province of China",
  "Türkiye",
  "United Kingdom",
  "United States",
]
