# Generated by Django 4.2 on 2023-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0004_alter_affiliation_organization_and_more"),
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="acceptance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="first_online_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="reception_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_licenses",
            field=models.ManyToManyField(
                related_name="related_articles", to="misc.license"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_materials",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="related_articles",
                to="misc.relatedmaterial",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="articleidentifier",
            name="identifier_type",
            field=models.CharField(
                choices=[("DOI", "Doi"), ("arXiv", "Arxiv")], max_length=255
            ),
        ),
    ]
