# Generated by Django 4.2.2 on 2023-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_abstract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="article",
            old_name="created_at",
            new_name="_created_at",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="updated_at",
            new_name="_updated_at",
        ),
        migrations.AddField(
            model_name="article",
            name="_files",
            field=models.ManyToManyField(to="articles.articlefile"),
        ),
    ]
