# Generated by Django 4.2.2 on 2023-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_alter_article__files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
