# Generated by Django 4.2.2 on 2023-07-07 15:12

from django.db import migrations, models
import django.db.models.deletion
import scoap3.articles.models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_alter_article_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="_files",
        ),
        migrations.AddField(
            model_name="articlefile",
            name="article_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="articlefile",
            name="file",
            field=models.FileField(
                upload_to=scoap3.articles.models.article_file_upload_path
            ),
        ),
    ]
