# Generated by Django 4.2.2 on 2023-07-11 08:57

from django.db import migrations
import scoap3.articles.models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_remove_article__files_articlefile_article_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlefile",
            name="file",
            field=scoap3.articles.models.CustomFileField(
                upload_to=scoap3.articles.models.article_file_upload_path
            ),
        ),
    ]
