# Generated by Django 4.2.2 on 2023-07-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_alter_articlefile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlefile",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_files",
                to="articles.article",
            ),
        ),
    ]
