# Generated by Django 4.2.3 on 2023-08-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_alter_articlefile_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleidentifier",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_identifiers",
                to="articles.article",
            ),
        ),
    ]
