# Generated by Django 4.2.5 on 2023-12-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_articleidentifier_article_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("check_license", models.BooleanField(default=False)),
                ("check_file_formats", models.BooleanField(default=False)),
                ("check_arxiv_category", models.BooleanField(default=False)),
                ("check_article_type", models.BooleanField(default=False)),
                ("check_doi_registration_time", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
