# Generated by Django 4.2.5 on 2023-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0012_compliancereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="check_article_type_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_arxiv_category_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_doi_registration_time_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_file_formats_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_license_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
