# Generated by Django 4.2.5 on 2024-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0013_compliancereport_check_article_type_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="check_authors_affiliation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_authors_affiliation_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
