# Generated by Django 4.2.5 on 2024-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0014_compliancereport_check_authors_affiliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="compliant",
            field=models.BooleanField(default=False),
        ),
    ]
