# Generated by Django 4.2.5 on 2024-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0015_compliancereport_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="check_required_file_formats",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_required_file_formats_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
