# Generated by Django 4.2.5 on 2024-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0016_compliancereport_check_required_file_formats_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliancereport",
            name="check_file_formats",
        ),
        migrations.RemoveField(
            model_name="compliancereport",
            name="check_file_formats_description",
        ),
    ]
