# Generated by Django 4.2.5 on 2024-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0017_remove_compliancereport_check_file_formats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlefile",
            name="filetype",
            field=models.TextField(blank=True, default=""),
        ),
    ]
