# Generated by Django 4.2.5 on 2024-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0018_articlefile_filetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="check_contains_funded_by_scoap3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_contains_funded_by_scoap3_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
