# Generated by Django 4.2 on 2023-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationinfo",
            name="artid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="page_end",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="page_start",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="volume_year",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
