# Generated by Django 4.2 on 2023-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0003_alter_license_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="copyright",
            name="holder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="copyright",
            name="statement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="copyright",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experimentalcollaboration",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="artid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="journal_issue",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="journal_volume",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="page_end",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="page_start",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="volume_year",
            field=models.CharField(max_length=255),
        ),
    ]
