# Generated by Django 4.2.2 on 2023-06-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0005_alter_affiliation_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
