# Generated by Django 4.2.2 on 2023-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0006_alter_license_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="value",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="articlearxivcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("qua.223", "Qua223"),
                    ("hep-lat", "Hep Lat"),
                    ("math.AG", "Math Ag"),
                    ("nucl-ex", "Nucl Ex"),
                    ("astro-ph.IM", "Astro Ph Im"),
                    ("math.RT", "Math Rt"),
                    ("math.QA", "Math Qa"),
                    ("math-ph", "Math Ph"),
                    ("cond-mat.mtrl-sci", "Cond Mat Mtrl Sci"),
                    ("astro-ph.GA", "Astro Ph Ga"),
                    ("astro-ph.CO", "Astro Ph Co"),
                    ("cond-mat.mes-hall", "Cond Mat Mes Hall"),
                    ("math.DG", "Math Dg"),
                    ("cond-mat.soft", "Cond Mat Soft"),
                    ("hep-ex", "Hep Ex"),
                    ("nucl-th", "Nucl Th"),
                    ("math.AT", "Math At"),
                    ("math.MP", "Math Mp"),
                    ("cond-mat.stat-mech", "Cond Mat Stat Mech"),
                    ("cond-mat.other", "Cond Mat Other"),
                    ("quant-ph", "Quant Ph"),
                    ("nlin.PS", "Nlin Ps"),
                    ("hep-ph", "Hep Ph"),
                    ("physics.ins-det", "Physics Ins Det"),
                    ("cond-mat.str-el", "Cond Mat Str El"),
                    ("gr-qc", "Gr Qc"),
                    ("hep-th", "Hep Th"),
                    ("astro-ph.HE", "Astro Ph He"),
                    ("cs.LG", "Cs Lg"),
                    ("astro-ph.SR", "Astro Ph Sr"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="journal_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
