# Generated by Django 4.2.2 on 2023-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_abstract_and_more"),
        ("authors", "0003_alter_author_first_name_alter_author_last_name"),
        ("misc", "0008_alter_publicationinfo_page_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="author_id",
            field=models.ManyToManyField(blank=True, null=True, to="authors.author"),
        ),
        migrations.AlterField(
            model_name="experimentalcollaboration",
            name="article_id",
            field=models.ManyToManyField(blank=True, null=True, to="articles.article"),
        ),
    ]
