# Generated by Django 4.2.2 on 2023-06-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0003_alter_author_first_name_alter_author_last_name"),
        ("misc", "0009_alter_affiliation_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="author_id",
            field=models.ManyToManyField(null=True, to="authors.author"),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misc.country",
            ),
        ),
    ]
