# Generated by Django 4.2.2 on 2023-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "misc",
            "0012_remove_experimentalcollaboration_experimental_collaboration_order",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
