# Generated by Django 4.2.2 on 2023-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0013_alter_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="value",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("url", "name")},
        ),
    ]
