# Generated by Django 4.2.3 on 2023-08-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_articleidentifier_article_id"),
        ("misc", "0015_alter_experimentalcollaboration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlearxivcategory",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_arxiv_category",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="publicationinfo",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_info",
                to="articles.article",
            ),
        ),
    ]
