# Generated by Django 4.2.5 on 2024-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0018_alter_publicationinfo_volume_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="organization",
            field=models.TextField(blank=True, default=""),
        ),
    ]
