# Generated by Django 4.2.5 on 2024-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0005_alter_author_article_id"),
        ("misc", "0019_alter_affiliation_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="author_id",
            field=models.ManyToManyField(
                blank=True, related_name="affiliations", to="authors.author"
            ),
        ),
    ]
